name: Deploy to WordPress.org
on:
  push
jobs:
  build:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev